import{S as m,N as h,P as w}from"./assets/vendor-B-mvldNl.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&l(a)}).observe(document,{childList:!0,subtree:!0});function d(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function l(e){if(e.ep)return;e.ep=!0;const t=d(e);fetch(e.href,t)}})();const p=(c,r,d,l)=>{let e=null;const t=()=>{window.innerWidth<1440&&!e&&(e=new m(c,{modules:[h,w],slidesPerView:1,spaceBetween:16,loop:!0,navigation:{nextEl:r,prevEl:d},pagination:{el:l,clickable:!0}})),window.innerWidth>=1440&&e&&(e.destroy(!0,!0),e=null)};t(),window.addEventListener("resize",t)};p(".titles-swiper",".titles-next",".titles-prev",".titles-pagination");p(".lines-swiper",".lines-next",".lines-prev",".lines-pagination");document.addEventListener("DOMContentLoaded",()=>{const c=document.querySelector(".menu-button"),r=c.querySelector(".icon"),d=document.querySelector(".modal"),l=document.querySelectorAll(".menu-list-item"),e=document.querySelector(".header");let t=!1;const a=`
<svg width="31" height="31" viewBox="0 0 31 31" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M5.16699 15.5H25.8337" stroke="white" stroke-width="1.66667" stroke-linecap="round" stroke-linejoin="round" />
  <path d="M5.16699 7.75H25.8337" stroke="white" stroke-width="1.66667" stroke-linecap="round" stroke-linejoin="round" />
  <path d="M5.16699 23.25H25.8337" stroke="white" stroke-width="1.66667" stroke-linecap="round" stroke-linejoin="round" />
</svg>
    `,n=`
<svg width="36" height="36" viewBox="0 0 36 36" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M30 30L6 6M30 6L6 30" stroke="white" stroke-opacity="0.7" stroke-width="2" stroke-linecap="round" />
</svg>
    `;c.addEventListener("click",()=>{t=!t,r.innerHTML=t?n:a,t?o():i()}),l.forEach(u=>u.addEventListener("click",()=>{i(),r.innerHTML=a,t=!1})),window.addEventListener("scroll",s);function o(){d.style.display="block"}function i(){d.style.display="none"}function s(){e&&(window.scrollY>60?e.classList.add("header-scroll"):e.classList.remove("header-scroll"))}});document.addEventListener("DOMContentLoaded",()=>{function c(){const n=document.getElementById("site-header");return n?n.offsetHeight:0}function r(n){const o=document.getElementById(n);if(!o)return;const i=c(),s=o.getBoundingClientRect().top+window.pageYOffset-i;window.scrollTo({top:s,behavior:"smooth"})}document.querySelectorAll(".navigation-item a").forEach(n=>{n.addEventListener("click",function(o){const i=this.getAttribute("href");if(!i)return;const[s,u]=i.split("#");if(!u)return;const f=window.location.pathname.split("/").pop();!(s===""||s==="./"||s===f||s==="./"+f)||!document.getElementById(u)||(o.preventDefault(),r(u),t(u))})});const l=document.querySelectorAll("section[id]"),e=document.querySelectorAll(".navigation-item");function t(n){e.forEach(i=>i.classList.remove("active"));const o=document.querySelector(`.navigation-item a[href*="#${n}"]`);o&&o.closest(".navigation-item").classList.add("active")}function a(){const n=window.pageYOffset+c()+100;l.forEach(o=>{const i=o.offsetTop,s=i+o.offsetHeight;n>=i&&n<s&&t(o.id)})}if(window.addEventListener("scroll",a),window.location.hash){const n=window.location.hash.substring(1);setTimeout(()=>{r(n),t(n)},300)}});
//# sourceMappingURL=index.js.map
